// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADBAOrZ0SAh_i4HhSVptqrioARcdniC9U',
    appId: '1:793669247885:web:f53e5d6a568f01251693c4',
    messagingSenderId: '793669247885',
    projectId: 'rawigo2-1e2ab',
    authDomain: 'rawigo2-1e2ab.firebaseapp.com',
    storageBucket: 'rawigo2-1e2ab.firebasestorage.app',
    measurementId: 'G-1FP77PL9YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7qvniI9uJA55z3vRfCQuhnRehMnA6OZ4',
    appId: '1:793669247885:android:4763685bd9af00601693c4',
    messagingSenderId: '793669247885',
    projectId: 'rawigo2-1e2ab',
    storageBucket: 'rawigo2-1e2ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZdYNJd06YJmz2YOUSVKoRRl1qEzs61k',
    appId: '1:793669247885:ios:8539afc86b216f931693c4',
    messagingSenderId: '793669247885',
    projectId: 'rawigo2-1e2ab',
    storageBucket: 'rawigo2-1e2ab.firebasestorage.app',
    iosBundleId: 'com.example.rawiGo',
  );
}
